apiVersion: v1
kind: Service
metadata:
  labels:
    app: jmeter
  name: jmeter
  namespace: jmeter
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 9270
  selector:
    job-name: jmeter
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}